version: '3.4'

services:
  movies2watch.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - ASPNETCORE_URLS=http://+:5000;https://+:5001
     
    ports:
     - "5000:5000"
     - "5001:5001"
